max_retry: 3
retry_status_codes: [429, 502, 503, 504]
retry_backoff_factor: 0.5
base_endpoint: "https://api-inference.huggingface.co/models/"
model_id: "gpt2"
params:
  max_new_tokens: 50
  num_return_sequences: 1
  temperature: 0.8
